# Generated by Django 2.2.6 on 2019-10-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('departure_date', models.DateTimeField()),
                ('eta', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=20)),
                ('arrived', models.BooleanField(default=False)),
                ('arrival_date', models.DateTimeField()),
            ],
        ),
    ]
