# Generated by Django 2.2.6 on 2019-10-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekord_api', '0002_auto_20191023_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='arrival_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='description',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
